version: 2

sources:
  - name: raw_ga4
    database: par-west-ai-dashboard   # BigQuery project
    schema: raw_ga4                   # BigQuery dataset
    tables:
      - name: daily_active_users
      - name: devices
      - name: four_weekly_active_users
      - name: locations
      - name: pages
      - name: tech_device_category_report
      - name: traffic_acquisition_session_default_channel_grouping_report
      - name: traffic_acquisition_session_source_medium_report
      - name: traffic_sources
      - name: user_acquisition_first_user_source_report
      - name: website_overview
      - name: weekly_active_users
      - name: weekly_events_report

  - name: raw_google_ads
    database: par-west-ai-dashboard
    schema: raw_google_ads
    tables:
      - name: account_performance_report
      - name: campaign
      - name: campaign_bidding_strategy
      - name: campaign_budget
      - name: campaign_criterion
      - name: campaign_label
      - name: click_view
      - name: customer
      - name: display_keyword_view
      - name: geographic_view
      - name: keyword_view
      - name: label
      - name: user_location_view

  - name: raw_klaviyo
    database: par-west-ai-dashboard
    schema: raw_klaviyo
    tables:
      - name: campaigns
      - name: events
      - name: flows
      - name: lists
      - name: metrics
      - name: profiles

  - name: raw_woocommerce
    database: par-west-ai-dashboard
    schema: raw_woocommerce
    tables:
      - name: coupons
      - name: customers
      - name: order_notes
      - name: orders
      - name: product_categories
      - name: product_variations
      - name: products
      - name: refunds
      - name: shipping_methods

  - name: raw_netsuite
    database: par-west-ai-dashboard
    schema: raw_netsuite
    tables:
      - name: contact
      - name: customer
      - name: inventoryitem
      - name: invoice
      - name: itemfulfillment
      - name: salesorder
