version: 2

models:
  - name: stg_netsuite_customer
    description: >
      Staged NetSuite customers from raw_netsuite.customers. One row per customer,
      exposing the internal id, primary email, company name, and create/modify timestamps.
    columns:
      - name: ns_customer_id
        description: "NetSuite internal customer id (cast to string)."
        tests:
          - not_null
          - unique

      - name: customer_email
        description: "Primary customer email, lowercased and trimmed."
        tests:
          - not_null:
              config:
                severity: warn

      - name: company_name
        description: "Customer company name from NetSuite."
        tests:
          - not_null:
              config:
                severity: warn

      - name: first_seen_at
        description: "Timestamp when the customer record was created in NetSuite."
        tests:
          - not_null

      - name: last_seen_at
        description: "Timestamp when the customer record was last modified in NetSuite."
        tests:
          - not_null

  # IMPORTANT: name must match the MODEL NAME (filename without .sql), not the alias.
  - name: stg_netsuite_salesorders
    description: >
      Staged NetSuite sales orders from raw_netsuite.salesorder. Incremental, partitioned by order_date,
      clustered by customer_email. Excludes VOID/CANCELLED orders.
    config:
      +on_schema_change: append_new_columns
      # (optional but OK to declare here too if you want the YAML to reflect SQL settings)
      # +contract: {enforced: true}
      # +materialized: incremental
    columns:
      - name: order_id
        tests: [ { not_null: {} }, { unique: {} } ]
      - name: order_date
        tests: [ { not_null: {} } ]
      - name: ns_customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_netsuite_customer')
                field: ns_customer_id
      - name: customer_email
        tests:
          - not_null:
              config: { severity: warn }
      - name: order_amount
        tests: [ { not_null: {} } ]
      - name: currency
        tests:
          - not_null:
              config: { severity: warn }
      - name: order_source
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['netsuite']
      - name: status
        tests:
          - not_null:
              config: { severity: warn }
